# Generated by Django 3.2.14 on 2022-07-25 11:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0002_auto_20220715_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='statements',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
