# Generated by Django 3.2.14 on 2022-07-25 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_statements'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='statements',
        ),
    ]
